"""Capella REST API client package."""

from couchbase_connect.capella.allowed_cidr import CapellaAllowedCIDR
from couchbase_connect.capella.bucket import CapellaBucket
from couchbase_connect.capella.certificate import CapellaCertificate, parse_x509_certificate
from couchbase_connect.capella.client import (
    CAPELLA_API_HOST,
    CAPELLA_DATABASE_ID,
    CAPELLA_DATABASE_NAME,
    CAPELLA_DEFAULT_API_HOST,
    CAPELLA_DEFAULT_PROJECT_NAME,
    CAPELLA_ORGANIZATION_ID,
    CAPELLA_ORGANIZATION_NAME,
    CAPELLA_PROJECT_ID,
    CAPELLA_PROJECT_NAME,
    CAPELLA_TOKEN,
    CAPELLA_USER_EMAIL,
    CAPELLA_USER_ID,
    CouchbaseCapella,
)
from couchbase_connect.capella.cluster import CapellaCluster, ClusterConfig, ServiceGroupConfig
from couchbase_connect.capella.connect import (
    connect_cluster,
    disconnect_cluster,
    normalize_connect_string,
)
from couchbase_connect.capella.connectivity import CapellaConnectivity
from couchbase_connect.capella.credentials import CapellaCredentials
from couchbase_connect.capella.exceptions import (
    CapellaAPIError,
    CapellaNotFoundError,
    UserNotConfiguredError,
)
from couchbase_connect.capella.models import (
    AllowedCIDRData,
    AvailabilityData,
    AvailabilityType,
    BucketStatsData,
    CapellaBucketData,
    CapellaOrgUserData,
    CertificateResponse,
    CloudProviderData,
    CloudType,
    ClusterData,
    ComputeData,
    CouchbaseServerData,
    CreateAllowedCidrRequest,
    CreateBucketRequest,
    CreateClusterRequest,
    CreateDatabaseCredentialRequest,
    CreateDatabaseCredentialResponse,
    CreateProjectRequest,
    CredentialData,
    DatabaseAccessEntry,
    DatabaseResourceBucketData,
    DatabaseResourceData,
    DatabaseResourceScopeData,
    DiskConfig,
    IdResponse,
    NodeConfig,
    OrganizationData,
    OrganizationPreferences,
    ProjectData,
    ResourcesData,
    ServiceGroupData,
    ServiceGroupRequest,
    State,
    StateWaitOperation,
    SupportData,
    SupportPlanType,
    TimeZoneType,
    UpdateDatabaseCredentialRequest,
)
from couchbase_connect.capella.organization import CapellaOrganization
from couchbase_connect.capella.project import CapellaProject
from couchbase_connect.capella.user import CapellaUser
from couchbase_connect.capella.utils import dump_model, model_validate, random_name

__all__ = [
    "AllowedCIDRData",
    "AvailabilityData",
    "AvailabilityType",
    "BucketStatsData",
    "CAPELLA_API_HOST",
    "CAPELLA_DATABASE_ID",
    "CAPELLA_DATABASE_NAME",
    "CAPELLA_DEFAULT_API_HOST",
    "CAPELLA_DEFAULT_PROJECT_NAME",
    "CAPELLA_ORGANIZATION_ID",
    "CAPELLA_ORGANIZATION_NAME",
    "CAPELLA_PROJECT_ID",
    "CAPELLA_PROJECT_NAME",
    "CAPELLA_TOKEN",
    "CAPELLA_USER_EMAIL",
    "CAPELLA_USER_ID",
    "CapellaAPIError",
    "CapellaAllowedCIDR",
    "CapellaBucket",
    "CapellaBucketData",
    "CapellaCertificate",
    "CapellaCluster",
    "CapellaConnectivity",
    "CapellaCredentials",
    "CapellaNotFoundError",
    "CapellaOrgUserData",
    "CapellaOrganization",
    "CapellaProject",
    "CapellaUser",
    "CertificateResponse",
    "CloudProviderData",
    "CloudType",
    "ClusterConfig",
    "ClusterData",
    "ComputeData",
    "CouchbaseCapella",
    "CouchbaseServerData",
    "CreateAllowedCidrRequest",
    "CreateBucketRequest",
    "CreateClusterRequest",
    "CreateDatabaseCredentialRequest",
    "CreateDatabaseCredentialResponse",
    "CreateProjectRequest",
    "CredentialData",
    "DatabaseAccessEntry",
    "DatabaseResourceBucketData",
    "DatabaseResourceData",
    "DatabaseResourceScopeData",
    "DiskConfig",
    "IdResponse",
    "NodeConfig",
    "OrganizationData",
    "OrganizationPreferences",
    "ProjectData",
    "ResourcesData",
    "ServiceGroupConfig",
    "ServiceGroupData",
    "ServiceGroupRequest",
    "State",
    "StateWaitOperation",
    "SupportData",
    "SupportPlanType",
    "TimeZoneType",
    "UpdateDatabaseCredentialRequest",
    "UserNotConfiguredError",
    "connect_cluster",
    "disconnect_cluster",
    "dump_model",
    "model_validate",
    "normalize_connect_string",
    "parse_x509_certificate",
    "random_name",
]
